### ISSUE TITLE
crash when using a gradient brush for stroke

### ISSUE THREAD

**Issue by gunrot** [QUItCoding/qnanopainter#13]
Hi,
seems that 

```
    // Set parent painter for brush
    QNanoBrush* b = const_cast<QNanoBrush*>(&brush);
    if (b) {
        b->setParentPainter(this);
    }
```

is missing in void QNanoPainter::setStrokeStyle(const QNanoBrush &brush).

Seeing this const_casts here and there ,  i would consider making setParentPainter const and the member 'parentPainter'  mutable.

**Comment by QUItCoding** [comment]
Thanks! Fixed with commit 3963dad.

It also adds examples into gallery with gradient and image pattern strokes so functionality can be confirmed.
