### ISSUE TITLE
Corrupt icon&text in perf test app with ANGLE and qt/dev (5.11)

### ISSUE THREAD

**Issue by alpqr** [QUItCoding/qnanopainter#19]
In qnanopainter_vs_qpainter_demo something goes wrong with the "icon&text" content on Windows with ANGLE and latest qtbase and qtdeclarative from dev, but only when using QNanoPainter:

![image](https://user-images.githubusercontent.com/7945881/32689538-e480c232-c6e6-11e7-82f0-32aaace06856.png)

![image](https://user-images.githubusercontent.com/7945881/32689541-f9788e0e-c6e6-11e7-807f-d4c3fcd5cf45.png)

![image](https://user-images.githubusercontent.com/7945881/32689542-06836060-c6e7-11e7-862e-d3b0c4f604ce.png)

**Comment by QUItCoding** [comment]
Thanks! Haven't really tested windows side myself... Now installed Qt 5.9.2 MinGW and saw the same issue. Removing QNanoImage::GENERATE_MIPMAPS from demoqnanoitempainter.cpp fixes this so ANGLE can't handle NanoVG mipmaps for some reason...?

**Comment by QUItCoding** [comment]
Disabled mipmaps for demo on windows for now with the patch above. How they work/not on different platforms can still be tested with gallery.

**Comment by gunrot** [comment]
Well this must be a regression in Qt, it used to work in qt 5.6.2. I made the angle patch at that time.
I now checked again with 5.6.2 and latest QNanopainter
did 
```cpp
//#ifndef Q_OS_WIN
    // Windows ANGLE seems to have issues with mipmaps, use those in all other platforms.
    // See: https://github.com/QUItCoding/qnanopainter/issues/19
    imageFlags |= QNanoImage::GENERATE_MIPMAPS;
//#endif
```
and the balls are there. Using Qt 5.9.1 only black rectangles are shown.

**Comment by alpqr** [comment]
Maybe caused by an ANGLE upgrade? The bundled ANGLE version could have been upgraded between 5.6 and 5.9. That can pull in plenty of changes from upstream.

**Comment by gunrot** [comment]
Sure, i got also got lots of flicker with angle on window resize since qt 5.8, but why was angle upgraded when it shows some regressions, so what were the advantages? It also shows that qt does not actually test angle well on windows, which is bad as we depend on it.
