### ISSUE TITLE
wrong usage of QCache for font and images

### ISSUE THREAD

**Issue by gunrot** [QUItCoding/qnanopainter#2]
Either you or I have a misunderstanding in how QCache works.
When reading documentation, i read that it takes ownership and deletes an item any time it wants.
But this way you cannot stay in sync with the font stored in fontstash. you also use new for data which is deleted with free. Also a font in use may not be in the cache, as any other insert can lead to removal and deletion. Next time you use this removed font you will add it again in font stash. 
Only q implicit shared objects could be used by doing insert(key,new QImage(myImage)). .
i made a change to fix that by not using the cache at all, but use nvgFindFont to find an existing font.

see commit ea9a287 at github.com/gunrot/qnanopainter ( also in the pull request now by accident, i don't have a proper understanding of this for now it seems)

Similar issues exist with the image caching, but there is no possibility in nanovg to find an image by name. So i would just change the QCache to a QMap to have a name to id mapping.
The current usage of Cache, will lead to images be forgotten in the nag store, as QCache will evict the dataeleemwnt but not remove the image from the store.so the next time the image is added agin in the store as it has been forgotten.
 

I also do not  think the caching should be on item level, but should be globally shared. so items using the same font and images can shared them.
But as i understand it, each item has its itempainter, which holds its own nvg context ( storing fonts and images) and its own painter.

This architecture seems to be not efficient if i want to use about 100 quicknanoitems on the screen. especially if they use the same fonts and or images.

so could the nvg context be shared between quicknanoitems?

Best regards,
Gunnar Roth

**Comment by QUItCoding** [comment]
QCache was used to also be able to track how much memory is used for fonts & images. But you are right that it wasn’t really optimal, that’s why there was TODO to think some other way. I think your approach works well so merged the whole pull request, this can be fine-tuned later.

I tried initially to implement font & image cache that would be shared among items but got into trouble with (un)loading dynamic items. You can try to solve that, but anyway 100 QNanoQuickItems probably isn’t very optimal approach, better to try making fewer items with more content.

**Comment by gunrot** [comment]
Thank you for merging.

Well 100 Items are just 10 x 10 items in a UI, which i would say is not that much ( actually we are dealing with about 500 items in some scenarios) , handling that in a big NanoItem would mean to make my own QuickItem system inside  to have  enabling an item, make visible, move an item, rotate an item, connect properties with own property binding, event handling keyboard navigation etc.

**Comment by QUItCoding** [comment]
Yes 10x10 items isn’t that much but as those are painting to separate FBOs Qt scene graph can’t batch the rendering that efficiently. But please test, haven’t tried more than few nano items at the same time.

**Comment by gunrot** [comment]
well the problem is see is that if i have 100 items with the same font, that the font is stored a 100 times. Same for images. i also have 100 nvg contexts, where i do not know why these cannot be shared between QNanoQuickItemPainter instances. are QNanoQuickItemPainter instances touched by different threads or is there one nano render thread?
