### ISSUE TITLE
include qmath.h instead of math.h

### ISSUE THREAD

**Issue by alpqr** [QUItCoding/qnanopainter#20]
When building against qtbase/dev with MSVC I found the following change was needed to get M_PI:

diff --git a/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.cpp b/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.cpp
index 96c9b8e..33176c4 100644
--- a/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.cpp
+++ b/examples/qnanopainter_vs_qpainter_demo/src/demoqpitem.cpp
@@ -3,7 +3,7 @@
 #include <QPen>
 #include <QPointF>
 #include <QFontDatabase>
-#include <math.h>
+#include <qmath.h>

 DemoQPItem::DemoQPItem(QQuickItem *parent)
     : QQuickPaintedItem(parent)

**Comment by QUItCoding** [comment]
Thanks! Hadn't tested MSVC only MinGV, fixed with _USE_MATH_DEFINES which worked at least for me.
