### ISSUE TITLE
Does it work on raspberry pi?

### ISSUE THREAD

**Issue by mkawserm** [QUItCoding/qnanopainter#30]
I am getting compilation errors

**Comment by mkawserm** [comment]
I am getting these errors

In file included from ../../QbLib/3rdparty/libqnanopainter/private/qnanobackendgl2.cpp:12:0:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘int glnvg__renderCreateTexture(void*, int, int, int, int, const unsigned char*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:742:33: error: ‘GL_UNPACK_ROW_LENGTH’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:743:33: error: ‘GL_UNPACK_SKIP_PIXELS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:744:33: error: ‘GL_UNPACK_SKIP_ROWS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:750:51: error: ‘GL_GENERATE_MIPMAP’ was not declared in this scope
   QNANO_GLFWRAPPER glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE);
                                                   ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘int glnvg__renderUpdateTexture(void*, int, int, int, int, int, const unsigned char*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:833:33: error: ‘GL_UNPACK_ROW_LENGTH’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:834:33: error: ‘GL_UNPACK_SKIP_PIXELS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_PIXELS, x);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:835:33: error: ‘GL_UNPACK_SKIP_ROWS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_ROWS, y);
                                 ^
Makefile:24582: recipe for target '_obj/qnanobackendgl2.o' failed
make: *** [_obj/qnanobackendgl2.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../../QbLib/3rdparty/libqnanopainter/private/qnanobackendgl3.cpp:12:0:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘int glnvg__renderCreate(void*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:691:52: error: ‘glGenVertexArrays’ was not declared in this scope
  QNANO_GLFWRAPPER glGenVertexArrays(1, &gl->vertArr);
                                                    ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘int glnvg__renderCreateTexture(void*, int, int, int, int, const unsigned char*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:742:33: error: ‘GL_UNPACK_ROW_LENGTH’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:743:33: error: ‘GL_UNPACK_SKIP_PIXELS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:744:33: error: ‘GL_UNPACK_SKIP_ROWS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:762:51: error: ‘GL_RED’ was not declared in this scope
   QNANO_GLFWRAPPER glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, w, h, 0, GL_RED, GL_UNSIGNED_BYTE, data);
                                                   ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘int glnvg__renderUpdateTexture(void*, int, int, int, int, int, const unsigned char*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:833:33: error: ‘GL_UNPACK_ROW_LENGTH’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:834:33: error: ‘GL_UNPACK_SKIP_PIXELS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_PIXELS, x);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:835:33: error: ‘GL_UNPACK_SKIP_ROWS’ was not declared in this scope
  QNANO_GLFWRAPPER glPixelStorei(GL_UNPACK_SKIP_ROWS, y);
                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:852:64: error: ‘GL_RED’ was not declared in this scope
   QNANO_GLFWRAPPER glTexSubImage2D(GL_TEXTURE_2D, 0, x,y, w,h, GL_RED, GL_UNSIGNED_BYTE, data);
                                                                ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘void glnvg__renderFlush(void*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:1212:49: error: ‘glBindVertexArray’ was not declared in this scope
   QNANO_GLFWRAPPER glBindVertexArray(gl->vertArr);
                                                 ^
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h: In function ‘void glnvg__renderDelete(void*)’:
../../QbLib/3rdparty/libqnanopainter/nanovg/nanovg_gl_wrapped.h:1534:56: error: ‘glDeleteVertexArrays’ was not declared in this scope
   QNANO_GLFWRAPPER glDeleteVertexArrays(1, &gl->vertArr);
                                                        ^
Makefile:24674: recipe for target '_obj/qnanobackendgl3.o' failed
make: *** [_obj/qnanobackendgl3.o] Error 1

**Comment by QUItCoding** [comment]
Looking at errors you are building with OpenGL 2 backend (qnanobackendgl2.cpp) and not finding those (GL_UNPACK_ROW_LENGTH, GL_UNPACK_SKIP_PIXELS etc.) declarations. They are not available if you are building for OpenGL ES 2.0, is that what you have on Raspberry Pi? By default libqnanopainter/include.pri includes desktop OpenGL on Linux, you can edit it by moving "linux:!android" few lines above into OpenGL ES side when building on Linux + GLES platform. Does it work then?

**Comment by mkawserm** [comment]
Yeah it's working now. Thank you.
Here is my modified include.pri



# Add this into include path
INCLUDEPATH += $$PWD/

# Use c++11 features
CONFIG += c++11

win32  {
    QT_CONFIG += opengles2 angle
    CONFIG( debug, debug|release ) {
        # debug
        LIBS+= -llibGLESV2d
    } else {
        # release
        LIBS+= -llibGLESV2
    }
}

# Enable this to get drawind debug information
#DEFINES += QNANO_DEBUG

# Enable this to let Qt include OpenGL headers
DEFINES += QNANO_QT_GL_INCLUDE

# This will enable GLES3 (disable to force GLES2)
DEFINES += QNANO_ENABLE_GLES3

equals(QT_MAJOR_VERSION, 5):greaterThan(QT_MINOR_VERSION, 7) {
    message("Building with Qt at least 5.8 so may enabled QNANO_USE_RENDERNODE")
    # Enable this to use QRenderNode (available since Qt 5.8.0) instead of QQuickFramebufferObject
    #DEFINES += QNANO_USE_RENDERNODE
}

# Configure the amount of logging in release build
CONFIG(release, debug|release) {
    message("QNanoPainter Relase build")
    #DEFINES += QT_NO_WARNING_OUTPUT
    DEFINES += QT_NO_DEBUG_OUTPUT
    DEFINES += QT_NO_INFO_OUTPUT
}

# Configure the amount of logging in debug build
CONFIG(debug, debug|release) {
    message("QNanoPainter Debug build")
    #DEFINES += QT_NO_WARNING_OUTPUT
    #DEFINES += QT_NO_DEBUG_OUTPUT
    DEFINES += QT_NO_INFO_OUTPUT
}

SOURCES +=  \
    $$PWD/qnanopainter.cpp \
    $$PWD/qnanocolor.cpp \
    $$PWD/qnanolineargradient.cpp \
    $$PWD/qnanoimagepattern.cpp \
    $$PWD/qnanoimage.cpp \
    $$PWD/qnanofont.cpp \
    $$PWD/qnanoradialgradient.cpp \
    $$PWD/qnanoboxgradient.cpp \
    $$PWD/qnanowindow.cpp \
    $$PWD/private/qnanodebug.cpp

HEADERS +=  \
    $$PWD/private/qnanobrush.h \
    $$PWD/qnanopainter.h \
    $$PWD/qnanocolor.h \
    $$PWD/qnanolineargradient.h \
    $$PWD/qnanoimagepattern.h \
    $$PWD/qnanoimage.h \
    $$PWD/qnanofont.h \
    $$PWD/qnanoradialgradient.h \
    $$PWD/qnanoboxgradient.h \
    $$PWD/private/qnanodataelement.h \
    $$PWD/private/qnanobackend.h \
    $$PWD/private/qnanobackendfactory.h \
    $$PWD/qnanowindow.h \
    $$PWD/private/qnanodebug.h

contains(QT, quick) {
    SOURCES +=  \
        $$PWD/qnanoquickitem.cpp \
        $$PWD/qnanoquickitempainter.cpp
    HEADERS +=  \
        $$PWD/qnanoquickitem.h \
        $$PWD/qnanoquickitempainter.h
}

contains(QT, widgets) {
    SOURCES +=  \
        $$PWD/qnanowidget.cpp
    HEADERS +=  \
        $$PWD/qnanowidget.h
}

# Note: Due to Angle, windows might use either OpenGL (desktop) or
#       openGL ES (angle) backend.
android | ios | windows | linux-rasp-* {
    message("Including QNanoPainter OpenGL ES backends")
HEADERS += \
    $$PWD/private/qnanobackendgles2.h \
    $$PWD/private/qnanobackendgles3.h
SOURCES +=  \
    $$PWD/private/qnanobackendgles2.cpp \
    $$PWD/private/qnanobackendgles3.cpp
}

osx | linux:!android | windows {
!linux-rasp-*{
    message("Including QNanoPainter OpenGL backends")
HEADERS += \
    $$PWD/private/qnanobackendgl2.h \
    $$PWD/private/qnanobackendgl3.h
SOURCES +=  \
    $$PWD/private/qnanobackendgl2.cpp \
    $$PWD/private/qnanobackendgl3.cpp
}
}

## Include NanoVG
SOURCES +=  $$PWD/nanovg/nanovg.c
HEADERS +=  $$PWD/nanovg/nanovg.h

RESOURCES += \
    $$PWD/libqnanopainterdata.qrc
