### ISSUE TITLE
How to set the Z value?

### ISSUE THREAD

**Issue by linuxaged** [QUItCoding/qnanopainter#36]
I want to paint path item covering other items in the same scene graph. how to set the z value when painting?

**Comment by QUItCoding** [comment]
You set the z property for QNanoQuickItem just like any other QML items ( http://doc.qt.io/qt-5/qquickitem.html ). So if you want item to be on top on Qt Quick scenegraph, set z to bigger value than other items.

**Comment by linuxaged** [comment]
I define MyCustomNanoQuickItem and export to QML, other items and nano path are all MyCustomNanoQuickItem's children, it seems that the nano path always painted at z=0

**Comment by QUItCoding** [comment]
In that kind of parent-children case you can set children z negative so they will be rendered under the parent. But that is not specific to QNanoPainter, just how Qt Quick behaves.
