### ISSUE TITLE
how to draw polygon like QPainter?

### ISSUE THREAD

**Issue by yqlicglingfei** [QUItCoding/qnanopainter#42]
I'd like to draw polygon, but i didn't find function like QPainter::drawPolygon.

**Comment by QUItCoding** [comment]
With this kind of API polygons are painted with moveTo() + lineTo(). So for example if you have polygon coordinates in a QVector you could do something like:

```
    QVector<QPoint> myPolyGon;
    myPolyGon << QPoint(30, 10) << QPoint(80, 20)
              << QPoint(150, 70) << QPoint(80, 60)
              << QPoint(10, 100);

    painter->beginPath();
    painter->moveTo(myPolyGon.first());
    for (int i=1; i < myPolyGon.size(); i++) {
        painter->lineTo(myPolyGon.at(i));
    }
    painter->closePath();
    painter->setLineWidth(2);
    painter->setFillStyle("#ff0000");
    painter->setStrokeStyle("#ffff00");
    painter->fill();
    painter->stroke();
```
![qnanopainter_polygon_example](https://user-images.githubusercontent.com/16169635/55162398-70abb900-5170-11e9-9f05-44d954686908.png)

This way you can make your own drawPolygon() method suitable for you needs.

**Comment by yqlicglingfei** [comment]
Yeah, it works well with your code. Thank you.
