### ISSUE TITLE
Fixed Qt6.0.0-beta compile errors, some runtime deprecation warnings remain, 'gallery'->mouse event boxes issue noticed.

### ISSUE THREAD

**Issue by NielsMayer** [QUItCoding/qnanopainter#59]
1. #58 -- a few more compilation errors fixed when compiling with Qt6.0.0-beta ( https://www.qt.io/blog/qt-6.0-beta-released ). As of "beta 2" the pull request allows compiling and running.
2. When running "gallery" I note a deprecation warning that arises for Qt6
`W libgallery_x86_64.so: qrc:/qnanopainter_features/main.qml:80:13: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }`
I decided to leave these errors alone in this pull request because fixing it is not "clean" -- there is no QML "ifdef" so some kind of dynamic loading hack of two different QML files would be needed: one file for Qt>=6.0 and another for Qt5.
3. For Qt6 with PR #58 applied, when in 'gallery'->'Mouse Events Boxes', a single giant box is drawn rather than the random assortment normally seen. The expected display only occurs after clicking the "Random" button. The above PR does not fix this issue, so I'm documenting it here in hope it can be resolved in the future.

![Screenshot 2020-11-04 at 9 04 40 PM](https://user-images.githubusercontent.com/6306083/98200907-76888500-1ee3-11eb-9508-e62bb3fb2e94.png)

**Comment by NielsMayer** [comment]
Enclosed is the compilation error output from the unpatched current "head" qnanopainter versus latest Qt6.0.0 beta5 -- these are the errors fixed by #58 
[qnanopainter-6.0.0-beta5-compile-errors.txt](https://github.com/QUItCoding/qnanopainter/files/5551024/qnanopainter-6.0.0-beta5-compile-errors.txt)

**Comment by NielsMayer** [comment]
I just tested the fixes in #58 against the latest Qt6.0.0 beta5 release and they still compile and run. 

Still present: The error in  in 'gallery'->'Mouse Events Boxes' where no boxes are drawn until "Random" is clicked (see image above).

**Comment by QUItCoding** [comment]
I tested QNanoPainter with Qt 6.0.0 RC during this weekend and fixed few issues. I think it works 100% now, also that 'Mouse Events Boxes' thing was fixed with https://github.com/QUItCoding/qnanopainter/commit/f4541f1a7ffc886a038ac93e1a546e47eff313fb

**Comment by NielsMayer** [comment]
I have confirmed these updates work correctly under Ubuntu with the released Qt6.0.0 ( https://www.qt.io/blog/qt-6.0-released ) and Qt5.15.2 .

One trivial change in all the example main.cpp files will silence a warning -- setAttribute(Qt::AA_EnableHighDpiScaling) is no longer needed for Qt6.... 

```
#if (QT_VERSION < 0x060000) //for Qt6, prevent warning: ‘Qt::AA_EnableHighDpiScaling’ is deprecated: High-DPI scaling is always enabled. This attribute no longer has any effect. [-Wdeprecated-declarations]
    QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif /* (QT_VERSION < 0x060000) */
```
