### ISSUE TITLE
Don't alter QT_NO_{DEBUG,WARNING,INFO}_OUTPUT in include.pri

### ISSUE THREAD

**Issue by rburchell** [QUItCoding/qnanopainter#61]
It's great that you have a .pri file that enables easy embedding into other projects. But I think it's a bit hostile that this .pri alters "global" defines that may affect the rest of the project unexpectedly. In particular, QT_NO_{WARNING,DEBUG,INFO}_OUTPUT I think should not be changed by the .pri, but set by the including project.

The reason I am filing this is I had log output disabled for an entire library that I linked qnanopainter into, and it took me quite some time to track down the reason _why_ I was no longer seeing useful logging output from my own code :)

**Comment by QUItCoding** [comment]
True, removed those defines from the include.pri with the above commit. Thanks!
