### ISSUE TITLE
Can it be compiled to a dynamic library？

### ISSUE THREAD

**Issue by leamus** [QUItCoding/qnanopainter#77]
Can it be compiled to a dynamic link library? What should I do if possible?

**Comment by mariuszmaximus** [comment]
replace in `CMakeLists.txt`
`add_library(qnanopainter` 
to 
`add_library(qnanopainter SHARED`

**Comment by NielsMayer** [comment]
Or in my  case, using QMake to produce an old-fashioned static lib archive (*.a) via subdir libqnanopainter6/libqnanopainter6.pro:

```
TEMPLATE = lib
equals(QT_MAJOR_VERSION, 6):greaterThan(QT_MINOR_VERSION,6) {
CONFIG += c++17                                          ## Qt>=6.7 uses c++17
}
CONFIG += qt staticlib
QT += core quick

include(include.pri)

android:equals(QT_MAJOR_VERSION, 6) {           ##Qt6 supports single architecture at a time.
message("$${_PRO_FILE_}: $${ANDROID_SDK_ROOT} for $${ANDROID_TARGET_ARCH} with Qt$${QT_VERSION} and $${ANDROID_ABIS}")
TARGET = qnanopainter_$${ANDROID_TARGET_ARCH}
}
else:android {                                  ##Qt5 supports multi-arch linking e.g., libqnanopainter/arm64-v8a/libqnanopainter_arm64-v8a.a libqnanopainter/x86_64/libqnanopainter_x86_64.a
message("$${_PRO_FILE_}: $${ANDROID_SDK_ROOT} for $${ANDROID_TARGET_ARCH} with Qt$${QT_VERSION} and $${ANDROID_ABIS}")
TARGET = $${ANDROID_TARGET_ARCH}/qnanopainter_$${ANDROID_TARGET_ARCH}
}
else:linux {
message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Linux")
TARGET = qnanopainter
}
else:win32 {
message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Windows")
TARGET = qnanopainter
}
else:equals(QT_ARCH,"wasm") {
message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Web-Assembly")
TARGET = qnanopainter
}
else {
error("Unsupported OS or configuration for $${_PRO_FILE_}")
}
```

**Comment by leamus** [comment]
> Or in my case, using QMake to produce an old-fashioned static lib archive (*.a) via subdir libqnanopainter6/libqnanopainter6.pro:
> 
> ```
> TEMPLATE = lib
> equals(QT_MAJOR_VERSION, 6):greaterThan(QT_MINOR_VERSION,6) {
> CONFIG += c++17                                          ## Qt>=6.7 uses c++17
> }
> CONFIG += qt staticlib
> QT += core quick
> 
> include(include.pri)
> 
> android:equals(QT_MAJOR_VERSION, 6) {           ##Qt6 supports single architecture at a time.
> message("$${_PRO_FILE_}: $${ANDROID_SDK_ROOT} for $${ANDROID_TARGET_ARCH} with Qt$${QT_VERSION} and $${ANDROID_ABIS}")
> TARGET = qnanopainter_$${ANDROID_TARGET_ARCH}
> }
> else:android {                                  ##Qt5 supports multi-arch linking e.g., libqnanopainter/arm64-v8a/libqnanopainter_arm64-v8a.a libqnanopainter/x86_64/libqnanopainter_x86_64.a
> message("$${_PRO_FILE_}: $${ANDROID_SDK_ROOT} for $${ANDROID_TARGET_ARCH} with Qt$${QT_VERSION} and $${ANDROID_ABIS}")
> TARGET = $${ANDROID_TARGET_ARCH}/qnanopainter_$${ANDROID_TARGET_ARCH}
> }
> else:linux {
> message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Linux")
> TARGET = qnanopainter
> }
> else:win32 {
> message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Windows")
> TARGET = qnanopainter
> }
> else:equals(QT_ARCH,"wasm") {
> message("$${_PRO_FILE_}: Qt$${QT_VERSION} for Web-Assembly")
> TARGET = qnanopainter
> }
> else {
> error("Unsupported OS or configuration for $${_PRO_FILE_}")
> }
> ```


thanks, I have successfully compiled the dynamic link library using your method:
  dymatic.pro:

> TEMPLATE = lib
> include(/path/to/qnanopainter-master/libqnanopainter/include.pri)

But when using CMake, some errors was reported.

**Comment by leamus** [comment]
I have resolved problems,thanks~
