### ISSUE TITLE
Can no longer compile on Linux Desktop

### ISSUE THREAD

**Issue by NielsMayer** [QUItCoding/qnanopainter#8]
After updating recently, I could no longer compile the latest sources for Linux Desktop (Ubuntu 14.04LTS , Qt 5.6 beta #303). Compilation and running on Android still works.

This may have to do with 37cf1c247d36baa8cccc15c545342c8b60ff89aa from 3ff178cc149ea9364414504afb999121e1545cab  
>"Merge pull request #1 from gunrot/master
>    windows build using angle (glesv2)
>    Also image&font cache changes."

It appears changes for building on windows weren't propagated or tested on the Linux desktop build??

The Linux desktop version can be built by adding the following lines to the change for windows in qnanopainter/libqnanopainter/include.pri:11
```
win32  {
    QT_CONFIG += opengles2 angle
}
+unix {
+    DEFINES += QT_OPENGL_ES_2
+}
```
Note that the above change for Linux desktop is the minimum change I could do to correct the compilation error. I am not sure it is "correct."

The "merge pull request #1" suggests the change to libqnanopainter/include.pro was to "use correct way to specify opengles2". For Linux/Unix, is there a "QT += " module which will correctly set the defines for opengles2? My change reverts to the removed code from the win32 include.pri, which is what gave me the hint to try "DEFINES += QT_OPENGL_ES_2" for the unix build.
```
 win32  {
-    LIBS += libglesv2.lib
-    DEFINES += QT_OPENGL_ES_2
+    QT_CONFIG += opengles2 angle
 }
```
NBL The following is the error output seen compiling on Linux desktop without the change made to qnanopainter/libqnanopainter/include.pri:

```
g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DQT_NO_INFO_OUTPUT -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../qnanopainter/examples/qnanopainter_vs_qpainter_demo -I/home/npm/android/src/shield/build-qnanopainter-Desktop_Qt_5_6_0_GCC_x86_64bit_in_usr_bin-Release/examples/qnanopainter_vs_qpainter_demo -I../../../qnanopainter/libqnanopainter -I/opt/Qt5.6.0-beta/5.6/gcc_64/include -I/opt/Qt5.6.0-beta/5.6/gcc_64/include/QtQuick -I/opt/Qt5.6.0-beta/5.6/gcc_64/include/QtGui -I/opt/Qt5.6.0-beta/5.6/gcc_64/include/QtQml -I/opt/Qt5.6.0-beta/5.6/gcc_64/include/QtNetwork -I/opt/Qt5.6.0-beta/5.6/gcc_64/include/QtCore -I/home/npm/android/src/shield/build-qnanopainter-Desktop_Qt_5_6_0_GCC_x86_64bit_in_usr_bin-Release/examples/qnanopainter_vs_qpainter_demo -I/opt/Qt5.6.0-beta/5.6/gcc_64/mkspecs/linux-g++ -o qnanopainter.o ../../../qnanopainter/libqnanopainter/qnanopainter.cpp
In file included from ../../../qnanopainter/libqnanopainter/qnanopainter.cpp:38:0:
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h: In function 'int glnvg__renderCreateTexture(void*, int, int, int, int, const unsigned char*)':
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:754:16: error: 'GL_UNPACK_ROW_LENGTH' was not declared in this scope
  glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:755:16: error: 'GL_UNPACK_SKIP_PIXELS' was not declared in this scope
  glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:756:16: error: 'GL_UNPACK_SKIP_ROWS' was not declared in this scope
  glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:762:34: error: 'GL_GENERATE_MIPMAP' was not declared in this scope
   glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE);
                                  ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:774:34: error: 'GL_RED' was not declared in this scope
   glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, w, h, 0, GL_RED, GL_UNSIGNED_BYTE, data);
                                  ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h: In function 'int glnvg__renderUpdateTexture(void*, int, int, int, int, int, const unsigned char*)':
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:832:16: error: 'GL_UNPACK_ROW_LENGTH' was not declared in this scope
  glPixelStorei(GL_UNPACK_ROW_LENGTH, tex->width);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:833:16: error: 'GL_UNPACK_SKIP_PIXELS' was not declared in this scope
  glPixelStorei(GL_UNPACK_SKIP_PIXELS, x);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:834:16: error: 'GL_UNPACK_SKIP_ROWS' was not declared in this scope
  glPixelStorei(GL_UNPACK_SKIP_ROWS, y);
                ^
../../../qnanopainter/libqnanopainter/nanovg/nanovg_gl.h:851:47: error: 'GL_RED' was not declared in this scope
   glTexSubImage2D(GL_TEXTURE_2D, 0, x,y, w,h, GL_RED, GL_UNSIGNED_BYTE, data);
                                               ^
make[1]: Leaving directory `/home/npm/android/src/shield/build-qnanopainter-Desktop_Qt_5_6_0_GCC_x86_64bit_in_usr_bin-Release/examples/qnanopainter_vs_qpainter_demo'
make[1]: *** [qnanopainter.o] Error 1
make: *** [sub-examples-qnanopainter_vs_qpainter_demo-make_first] Error 2
14:47:54: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project qnanopainter (kit: Desktop Qt 5.6.0 GCC (x86 64bit in /usr/bin))
When executing step "Make"
```

**Comment by gunrot** [comment]
Hi Nils , well I suppose QT_CONFIG= opengles2 would be the correct way for linux,
or QT_CONFIG=opengl for OpenGL. 
Using OpenGL would maybe get in trouble with the    QCoreApplication::setAttribute(Qt::AA_UseOpenGLES);
calls.so maybe they should be wrapped in #idef QT_OPENGL_ES_2 #endif.

But you said it compile before on linux? Before my win32 specific change?

Regards,
Gunnar

**Comment by NielsMayer** [comment]
Gunnar --

Yes. it compiled previously on Linux, and after adding:
```linux {
    DEFINES += QT_OPENGL_ES_2
}```

It compiles&runs successfully, again.

QT_CONFIG appears to be completely ignored in Linux??

**Comment by gunrot** [comment]
> Am 10.01.2016 um 04:23 schrieb Niels Mayer <notifications@github.com>:
> 
> Gunnar --
> 
> Yes. it compiled previously on Linux, and after adding:
> linux {
> DEFINES += QT_OPENGL_ES_2
> }
> 
> It compiles&runs successfully, again.
> 
> QT_CONFIG appears to be completely ignored in Linux??
> 
> 
Well did you try with adding 
linux {
QT_CONFIG += opengles
}
instead ?

II would lie to understand which of my changes rendered the code unbuildable on linux.
I have only windows and mason at hand.


Regards,
Gunnar

**Comment by NielsMayer** [comment]
I can add
```linux {
QT_CONFIG += anytextiwantitdoesntmatter
}```
And the same thing will happen. QT_CONFIG doesn't do anything on my setup or system. It appears to be ignored.

**Comment by gunrot** [comment]
i figured out what is the correct way for linux. i still have no clue why it ever worked for you.
please test my fixopengllinux branch.

**Comment by NielsMayer** [comment]
I compiled&ran this revision of qnanopainter, 74054643201583b890d8dbdf9e4029ff2626477d, successfully on Linux Desktop, resolving issue #8.

**Comment by QUItCoding** [comment]
Linux should be working now with c7f532a.

**Comment by NielsMayer** [comment]
I verify that the "master" branch with c7f532ac3a9dee51935f633080c43a0fb2d50b0c now builds and runs on Linux desktop.

Thanks.
